### ISSUE TITLE
Extract boot.img or init_boot.img from Delta (maybe) payload

### ISSUE THREAD

**Issue by Rt39** [tobyxdd/android-ota-payload-extractor#6]
I'm a OnePlus user and I want to extract a full OTA, I've got the same problem as #4 saying its delta payload. I only want to exact the `init_boot.img` file for rooting, so even if the [python version](https://github.com/vm03/payload_dumper) cannot exact all the files, it works fine for me, but this program won't exact anything. I'm here to ask if this program could add the feature of extracting part of the imgs even it cannot exact all.

Here is the information about the OTA:
```
FILE_HASH=lB3Bowg24rmpf1MwJA3FAaYOUGl3Q8GssIKhum2zWzo=
FILE_SIZE=7631160751
METADATA_HASH=2wiZUXE/5xURtFkUxB+F+Kz10Fway7EPBTNnT1uieqQ=
METADATA_SIZE=290530
ota_target_version=PHB110_11.A.29_0290_202310192011
oplus_rom_version=V13.1.0
security_patch=2023-10-05
security_patch_vendor=2023-10-05
oplus_update_engine_verify_disable=0
oplus_separate_soft=22811
```
You can get it from

https://gauss-componentotacostmanual-cn.allawnfs.com/remove-a013fbdf98c074dedba31969fe467624/component-ota/23/10/23/3139a5770e414640ad62f5406b5b9e26.zip

https://gauss-compotacostauto-cn.allawnfs.com/remove-a013fbdf98c074dedba31969fe467624/component-ota/23/10/23/3139a5770e414640ad62f5406b5b9e26.zip

https://gauss-otacostmanual-cn.allawnfs.com/remove-a013fbdf98c074dedba31969fe467624/component-ota/23/10/23/3139a5770e414640ad62f5406b5b9e26.zip

https://componentota-manual-cn.allawnfs.com/component-ota/23/10/23/3139a5770e414640ad62f5406b5b9e26.zip

Here is the exception the python version payload_dumper get:
```
Processing vendor partition......................................................................Traceback (most recent call last):
  File "D:\misc\3139a5770e414640ad62f5406b5b9e26\payload_dumper-master\payload_dumper.py", line 157, in <module>
    dump_part(part)
  File "D:\misc\3139a5770e414640ad62f5406b5b9e26\payload_dumper-master\payload_dumper.py", line 109, in dump_part
    data = data_for_op(op,out_file,old_file)
  File "D:\misc\3139a5770e414640ad62f5406b5b9e26\payload_dumper-master\payload_dumper.py", line 44, in data_for_op
    data = dec.decompress(data)
_lzma.LZMAError: Input format not supported by decoder
```

**Comment by tobyxdd** [comment]
Will look into this next week

**Comment by maximiac** [comment]
I get the same error, and every dumper I try it always closes itself immediately...

**Comment by rainwashed** [comment]
soo, im guessing this is dead now?

**Comment by MattTheTekie** [comment]
yes
